### ISSUE TITLE
Wiki/documentation link is broken

### ISSUE THREAD

**Issue by djzwerg** [backdrop-contrib/webform2pdf#2]
Please update the link. I'm looking for help according to the creation of individual PDF templates and fount the broken link.

**Comment by bugfolder** [comment]
Where is the broken link you are referring to?

**Comment by djzwerg** [comment]
@bugfolder I tried the link at the readme-file.

**Comment by bugfolder** [comment]
That link is

https://github.com/backdrop-contrib/webform2pdf/wiki

Which does correctly lead to the Wiki. However, there's nothing (yet) in the wiki. It being a Wiki, anyone is free to add.

"Additional documentation is in the wiki" is the suggested language for READMEs, but until there's something there, perhaps "Any additional documentation will be found in the wiki" might be more accurate.

**Comment by djzwerg** [comment]
@bugfolder if I click on that link I will be redirected to the release page. Maybe this tab is disabled?

**Comment by bugfolder** [comment]
Oh that's interesting. If I'm logged out of Github, I get redirected to the release page as well.

But that's only if there's no wiki page yet. OK, learned something new. I should remove that line from the README until there's something in the wiki.

(Sorry, by the way, that there's no further documentation on creating PDF templates, though things should work pretty much the way they do on Drupal, so any Drupal docs you can find might be helpful.)

**Comment by djzwerg** [comment]
Ok, thanks. I think we can close this issue ;-)
